apiVersion: v1
kind: Service
metadata:
  name: openblog-service
  namespace: openblog
  labels:
    app: openblog
    ref: stage
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
    - name: http-metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30006
  selector:
    app: openblog
    ref: stage
